-- COMBINED PRODUCTION SCHEMA
-- Auto-generated by Granite Post Deployment

-- Support extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "citext";

SET search_path = public, extensions;



----------------------------------------------------
-- MIGRATION: 001_profiles_roles.sql
----------------------------------------------------

-- ============================================================
-- 001_profiles_roles.sql
-- Profiles, user roles, shared helper functions, and RLS
-- Run first — all other migrations depend on the RBAC functions.
-- ============================================================

-- ── Extensions ───────────────────────────────────────────────────────────────
-- extension moved to top
-- extension moved to top

-- ── Shared trigger: set updated_at on every UPDATE ───────────────────────────
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── Enum: staff roles ─────────────────────────────────────────────────────────
create type user_role as enum ('ADMIN', 'EDITOR', 'AUTHOR', 'MODERATOR');

-- ── profiles ──────────────────────────────────────────────────────────────────
-- One row per auth.users row. Auto-created by trigger on sign-up.
create table profiles (
  id              uuid        primary key references auth.users(id) on delete cascade,
  full_name       text,
  avatar_url      text,
  bio             text,
  twitter_handle  text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create trigger trg_profiles_updated_at
  before update on profiles
  for each row execute procedure set_updated_at();

-- Auto-create profile row when a new auth.users row is inserted.
create or replace function handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger trg_on_auth_user_created
  after insert on auth.users
  for each row execute procedure handle_new_user();

-- ── user_roles ────────────────────────────────────────────────────────────────
-- One role per user (single-role model; extend to many-to-many if needed later).
create table user_roles (
  id          uuid        primary key default gen_random_uuid(),
  user_id     uuid        not null references auth.users(id) on delete cascade,
  role        user_role   not null,
  granted_by  uuid        references auth.users(id) on delete set null,
  created_at  timestamptz not null default now(),
  constraint uq_user_roles_user_id unique (user_id)
);

create index idx_user_roles_user_id on user_roles(user_id);

-- ── RBAC helper functions ─────────────────────────────────────────────────────
-- These are called inside RLS policies on every table.
-- security definer + hardened search_path prevents privilege escalation.

create or replace function is_admin()
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from user_roles
    where user_id = auth.uid() and role = 'ADMIN'
  );
$$;

create or replace function is_editor()
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from user_roles
    where user_id = auth.uid() and role in ('ADMIN', 'EDITOR')
  );
$$;

create or replace function is_author()
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from user_roles
    where user_id = auth.uid() and role in ('ADMIN', 'EDITOR', 'AUTHOR')
  );
$$;

create or replace function is_moderator()
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from user_roles
    where user_id = auth.uid() and role in ('ADMIN', 'EDITOR', 'MODERATOR')
  );
$$;

create or replace function is_staff()
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from user_roles where user_id = auth.uid()
  );
$$;

-- ── RLS: profiles ────────────────────────────────────────────────────────────
alter table profiles enable row level security;

create policy "Public can view profiles"
  on profiles for select
  using (true);

create policy "Users can update their own profile"
  on profiles for update
  using (auth.uid() = id);

-- ── RLS: user_roles ──────────────────────────────────────────────────────────
alter table user_roles enable row level security;

create policy "Staff can view roles"
  on user_roles for select
  using (is_staff());

create policy "Admins can manage roles"
  on user_roles for all
  using (is_admin());


----------------------------------------------------
-- MIGRATION: 002_taxonomy.sql
----------------------------------------------------

-- ============================================================
-- 002_taxonomy.sql
-- Categories and Tags
-- Depends on: 001_profiles_roles.sql (set_updated_at, RBAC functions)
-- ============================================================

-- ── categories ───────────────────────────────────────────────────────────────
create table categories (
  id               uuid        primary key default gen_random_uuid(),
  name             text        not null,
  slug             citext      not null,
  description      text,
  seo_title        text,
  seo_description  text,
  -- Hierarchical support (one level of nesting is sufficient for news)
  parent_id        uuid        references categories(id) on delete set null,
  display_order    int         not null default 0,
  is_active        boolean     not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint uq_categories_slug unique (slug),
  constraint chk_no_self_parent check (parent_id <> id)
);

-- Fast lookup by slug (all queries use this)
create index idx_categories_slug        on categories(slug);
-- Homepage nav ordering
create index idx_categories_order       on categories(display_order) where is_active = true;
-- Subcategory lookups
create index idx_categories_parent_id   on categories(parent_id) where parent_id is not null;

create trigger trg_categories_updated_at
  before update on categories
  for each row execute procedure set_updated_at();

-- ── tags ─────────────────────────────────────────────────────────────────────
create table tags (
  id          uuid        primary key default gen_random_uuid(),
  name        text        not null,
  slug        citext      not null,
  created_at  timestamptz not null default now(),
  constraint uq_tags_slug  unique (slug),
  constraint uq_tags_name  unique (name)
);

create index idx_tags_slug on tags(slug);

-- ── RLS: categories ──────────────────────────────────────────────────────────
alter table categories enable row level security;

create policy "Categories are publicly readable"
  on categories for select
  using (true);

create policy "Editors can manage categories"
  on categories for all
  using (is_editor());

-- ── RLS: tags ────────────────────────────────────────────────────────────────
alter table tags enable row level security;

create policy "Tags are publicly readable"
  on tags for select
  using (true);

create policy "Authors can manage tags"
  on tags for all
  using (is_author());


----------------------------------------------------
-- MIGRATION: 003_articles.sql
----------------------------------------------------

-- ============================================================
-- 003_articles.sql
-- Articles and article_tags pivot table
-- Depends on: 001_profiles_roles.sql, 002_taxonomy.sql
-- ============================================================

-- ── Enum: editorial workflow states ──────────────────────────────────────────
create type article_status as enum ('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED');

-- ── articles ──────────────────────────────────────────────────────────────────
create table articles (
  id                   uuid           primary key default gen_random_uuid(),

  -- ── Core content ──────────────────────────────────────────────────────────
  title                text           not null,
  slug                 citext         not null,
  excerpt              text,
  -- HTML body stored as text; sanitised before insert via server action.
  body_html            text           not null default '',

  -- ── Editorial classification ───────────────────────────────────────────────
  status               article_status not null default 'DRAFT',
  category_id          uuid           references categories(id) on delete set null,
  author_id            uuid           not null references auth.users(id) on delete restrict,

  -- ── Hero image ────────────────────────────────────────────────────────────
  hero_image_url       text,
  hero_image_alt       text,
  hero_image_caption   text,
  hero_image_credit    text,   -- Photographer / agency credit line

  -- ── Editorial signals ─────────────────────────────────────────────────────
  -- NULL = not featured. 1 = lead hero. Higher integers = lower priority.
  featured_rank        smallint,
  is_breaking          boolean        not null default false,
  -- If set, is_breaking should be auto-cleared after this timestamp.
  breaking_expires_at  timestamptz,

  -- ── SEO / Open Graph overrides ────────────────────────────────────────────
  og_title             text,
  og_description       text,
  -- Must be >= 1200 × 630 px per OG spec; validated at application layer.
  og_image_url         text,
  -- Set only when the canonical differs from /article/slug (e.g. syndication).
  canonical_url        text,

  -- ── Denormalised metrics (updated by RPC, never by direct client writes) ──
  view_count           bigint         not null default 0,

  -- ── Timestamps ────────────────────────────────────────────────────────────
  published_at         timestamptz,
  created_at           timestamptz    not null default now(),
  updated_at           timestamptz    not null default now(),

  -- ── Constraints ───────────────────────────────────────────────────────────
  constraint uq_articles_slug           unique (slug),
  constraint chk_featured_rank          check (featured_rank is null or featured_rank > 0),
  constraint chk_breaking_expiry        check (
    breaking_expires_at is null or is_breaking = true
  ),
  constraint chk_published_at_required  check (
    status <> 'PUBLISHED' or published_at is not null
  ),
  constraint chk_view_count_nonneg      check (view_count >= 0)
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Primary feed query: published articles by date
create index idx_articles_status_published
  on articles(status, published_at desc);

-- Slug lookup (article page, ISR revalidation)
create index idx_articles_slug
  on articles(slug);

-- Category page: published articles in a category
create index idx_articles_category_status
  on articles(category_id, published_at desc)
  where status = 'PUBLISHED';

-- Author management view
create index idx_articles_author_status
  on articles(author_id, updated_at desc);

-- Homepage hero query: featured articles
create index idx_articles_featured_rank
  on articles(featured_rank asc, published_at desc)
  where status = 'PUBLISHED' and featured_rank is not null;

-- Breaking bar: active breaking news
create index idx_articles_breaking
  on articles(is_breaking, published_at desc)
  where is_breaking = true and status = 'PUBLISHED';

-- RSS / sitemap: all published, ordered by date
create index idx_articles_published_desc
  on articles(published_at desc)
  where status = 'PUBLISHED';

create trigger trg_articles_updated_at
  before update on articles
  for each row execute procedure set_updated_at();

-- ── article_tags ──────────────────────────────────────────────────────────────
create table article_tags (
  article_id  uuid not null references articles(id) on delete cascade,
  tag_id      uuid not null references tags(id)     on delete cascade,
  primary key (article_id, tag_id)
);

-- Reverse lookup: all articles for a given tag
create index idx_article_tags_tag_id on article_tags(tag_id);

-- ── RLS: articles ────────────────────────────────────────────────────────────
alter table articles enable row level security;

-- Public can only see PUBLISHED articles.
-- Staff (any role) can see all statuses.
create policy "Published articles are public"
  on articles for select
  using (status = 'PUBLISHED' or is_author());

create policy "Authors can create articles"
  on articles for insert
  with check (is_author() and auth.uid() = author_id);

-- Authors edit their own; editors and admins edit any.
create policy "Authors update own articles; editors update any"
  on articles for update
  using (
    is_editor()
    or (is_author() and auth.uid() = author_id)
  );

create policy "Editors can delete articles"
  on articles for delete
  using (is_editor());

-- ── RLS: article_tags ────────────────────────────────────────────────────────
alter table article_tags enable row level security;

create policy "Article tags are publicly readable"
  on article_tags for select
  using (true);

create policy "Authors can manage article tags"
  on article_tags for all
  using (is_author());


----------------------------------------------------
-- MIGRATION: 004_media.sql
----------------------------------------------------

-- ============================================================
-- 004_media.sql
-- Media assets (backed by Supabase Storage bucket "media")
-- Depends on: 001_profiles_roles.sql, 003_articles.sql
-- ============================================================

-- ── Enum: asset type ─────────────────────────────────────────────────────────
create type media_type as enum ('IMAGE', 'VIDEO', 'DOCUMENT');

-- ── media ─────────────────────────────────────────────────────────────────────
-- One row per file uploaded to Supabase Storage.
-- Deleting this row should be paired with deleting the storage object
-- (handled in the application layer, not a DB trigger, to avoid coupling).
create table media (
  id            uuid        primary key default gen_random_uuid(),

  -- Storage
  filename      text        not null,
  storage_path  text        not null,  -- Path within the "media" bucket
  url           text        not null,  -- Public CDN URL

  -- Descriptive metadata
  alt_text      text,
  credit        text,        -- Photographer / agency / copyright line
  caption       text,

  -- Technical metadata
  mime_type     text        not null,
  media_type    media_type  not null default 'IMAGE',
  width         int,
  height        int,
  size_bytes    bigint      not null default 0,

  -- Ownership
  uploaded_by   uuid        not null references auth.users(id) on delete restrict,

  created_at    timestamptz not null default now(),

  constraint uq_media_storage_path  unique (storage_path),
  constraint uq_media_url           unique (url),
  constraint chk_media_width        check (width  is null or width  > 0),
  constraint chk_media_height       check (height is null or height > 0),
  constraint chk_media_size         check (size_bytes >= 0)
);

create index idx_media_uploaded_by_date on media(uploaded_by, created_at desc);
create index idx_media_type_date        on media(media_type,  created_at desc);

-- ── article_media ─────────────────────────────────────────────────────────────
-- Optional junction: attach multiple media assets to an article in-body.
-- The hero image is stored directly on articles.hero_image_url for simplicity;
-- this table handles body / gallery assets and future multi-image features.
create table article_media (
  id          uuid        primary key default gen_random_uuid(),
  article_id  uuid        not null references articles(id) on delete cascade,
  media_id    uuid        not null references media(id)    on delete restrict,
  -- Ordering within the article
  position    smallint    not null default 0,
  -- Role of the asset in the article context
  role        text        not null default 'body',
    -- 'hero'    – alternative/duplicate hero reference
    -- 'body'    – inline image in article body
    -- 'gallery' – gallery item
  created_at  timestamptz not null default now(),

  constraint uq_article_media_pair unique (article_id, media_id),
  constraint chk_article_media_role check (role in ('hero', 'body', 'gallery'))
);

create index idx_article_media_article on article_media(article_id, position asc);
create index idx_article_media_media   on article_media(media_id);

-- ── RLS: media ───────────────────────────────────────────────────────────────
alter table media         enable row level security;
alter table article_media enable row level security;

-- Public can read all media metadata (URLs are CDN-public anyway)
create policy "Media is publicly readable"
  on media for select
  using (true);

create policy "Staff can upload media"
  on media for insert
  with check (is_author());

-- Uploaders can update their own; editors can update any
create policy "Uploaders and editors can update media"
  on media for update
  using (
    is_editor()
    or (is_author() and uploaded_by = auth.uid())
  );

create policy "Editors can delete media"
  on media for delete
  using (is_editor());

-- article_media
create policy "Article media is publicly readable"
  on article_media for select
  using (true);

create policy "Authors can manage article media"
  on article_media for all
  using (is_author());


----------------------------------------------------
-- MIGRATION: 004_site_pages.sql
----------------------------------------------------

-- ── site_pages ──────────────────────────────────────────────────────────────
-- Stores CMS-managed content for static informational pages.
-- Public: SELECT only.  Staff (ADMIN/EDITOR): INSERT, UPDATE.

CREATE TABLE IF NOT EXISTS site_pages (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  slug             text        UNIQUE NOT NULL,
  title            text        NOT NULL,
  meta_description text,
  content_html     text        NOT NULL DEFAULT '',
  updated_at       timestamptz NOT NULL DEFAULT now()
);

-- Index for slug lookups (public page renderer + admin editor)
CREATE INDEX IF NOT EXISTS site_pages_slug_idx ON site_pages (slug);

-- ── RLS ─────────────────────────────────────────────────────────────────────
ALTER TABLE site_pages ENABLE ROW LEVEL SECURITY;

-- Anyone can read published pages
CREATE POLICY "Public read site_pages"
  ON site_pages FOR SELECT
  USING (true);

-- Only admins and editors can update
CREATE POLICY "Staff update site_pages"
  ON site_pages FOR UPDATE
  USING (is_admin() OR is_editor())
  WITH CHECK (is_admin() OR is_editor());

-- Only admins can insert new pages
CREATE POLICY "Admin insert site_pages"
  ON site_pages FOR INSERT
  WITH CHECK (is_admin());

-- ── Seed data ────────────────────────────────────────────────────────────────
INSERT INTO site_pages (slug, title, meta_description, content_html) VALUES

('about',
 'About Us',
 'Zimbabwe News Online is your trusted source for breaking news and in-depth reporting from Zimbabwe and across Africa.',
 '<h2>About Zimbabwe News Online</h2>
<p>Zimbabwe News Online is an independent digital news platform dedicated to delivering accurate, timely, and impartial reporting on events in Zimbabwe and across the African continent.</p>
<p>Founded with the mission of keeping Zimbabweans at home and in the diaspora informed, we cover politics, business, sport, health, technology, entertainment, and more.</p>
<h2>Our Mission</h2>
<p>To be Zimbabwe''s most trusted digital news platform — holding power to account, amplifying community voices, and delivering journalism that matters.</p>
<h2>Editorial Standards</h2>
<p>We follow rigorous editorial standards. All stories are verified before publication. Corrections are issued promptly and transparently.</p>'),

('contact',
 'Contact Us',
 'Contact the Zimbabwe News Online newsroom.',
 '<h2>Get in Touch</h2>
<p>We welcome tips, feedback, and enquiries from readers.</p>
<h3>Newsroom</h3>
<p>For news tips, press releases, and story pitches:<br><a href="mailto:newsroom@zimbabwenewsonline.com">newsroom@zimbabwenewsonline.com</a></p>
<h3>Editorial Complaints</h3>
<p>To raise a concern about an article or our editorial standards:<br><a href="mailto:editor@zimbabwenewsonline.com">editor@zimbabwenewsonline.com</a></p>
<h3>Advertising</h3>
<p>For advertising and partnership enquiries:<br><a href="mailto:ads@zimbabwenewsonline.com">ads@zimbabwenewsonline.com</a></p>
<h3>Corrections</h3>
<p>To request a correction, please email <a href="mailto:corrections@zimbabwenewsonline.com">corrections@zimbabwenewsonline.com</a> with the article URL and details of the error.</p>'),

('editorial-policy',
 'Editorial Policy',
 'Our editorial standards, values, and policy.',
 '<h2>Our Editorial Standards</h2>
<p>Zimbabwe News Online is committed to accuracy, fairness, and independence in all our reporting.</p>
<h2>Accuracy</h2>
<p>We strive to ensure all published content is accurate and verifiable. When errors occur, we correct them promptly and transparently via our <a href="/corrections">Corrections</a> page.</p>
<h2>Impartiality</h2>
<p>We report facts without fear or favour, giving appropriate weight to all sides of a story. Opinions are clearly labelled and separated from news reporting.</p>
<h2>Independence</h2>
<p>Our editorial decisions are made independently of advertisers, political parties, and commercial interests. No external party has editorial control over our content.</p>
<h2>Sources</h2>
<p>We verify information with multiple sources before publication. Anonymous sources are used only when necessary and with editorial approval.</p>
<h2>Conflicts of Interest</h2>
<p>Staff must declare any potential conflicts of interest. We do not accept gifts or payments that could compromise our editorial integrity.</p>'),

('corrections',
 'Corrections',
 'How Zimbabwe News Online handles corrections and updates to published articles.',
 '<h2>Our Corrections Policy</h2>
<p>Zimbabwe News Online is committed to accuracy. When we make mistakes, we correct them promptly and transparently.</p>
<h2>How to Request a Correction</h2>
<p>If you believe an article contains a factual error, please contact our editorial team at <a href="mailto:corrections@zimbabwenewsonline.com">corrections@zimbabwenewsonline.com</a>.</p>
<p>Please include:</p>
<ul>
<li>The URL of the article</li>
<li>The specific error you have identified</li>
<li>Supporting evidence or sources</li>
<li>Your contact details (not published)</li>
</ul>
<h2>Our Process</h2>
<p>We review all correction requests within 48 hours. Verified corrections are updated in the article text with a correction notice appended, noting what was changed and when.</p>'),

('ownership',
 'Ownership',
 'Information about the ownership and funding of Zimbabwe News Online.',
 '<h2>Ownership &amp; Funding</h2>
<p>Zimbabwe News Online is an independently owned digital news platform. We are committed to full transparency about our ownership structure and funding sources.</p>
<h2>Editorial Independence</h2>
<p>Our editorial team operates with complete independence from our ownership structure. Owners and investors do not influence editorial decisions, story selection, or the framing of news coverage.</p>
<h2>Funding</h2>
<p>Zimbabwe News Online is funded through digital advertising and reader support. We do not accept funding that comes with conditions attached to our editorial output.</p>
<h2>Transparency</h2>
<p>For ownership enquiries, contact <a href="mailto:editor@zimbabwenewsonline.com">editor@zimbabwenewsonline.com</a>.</p>'),

('privacy-policy',
 'Privacy Policy',
 'How Zimbabwe News Online collects, uses, and protects your personal data.',
 '<h2>Privacy Policy</h2>
<p>This policy explains how Zimbabwe News Online (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) collects, uses, and protects your personal information when you use our website.</p>
<h2>Information We Collect</h2>
<ul>
<li><strong>Newsletter subscribers:</strong> email address only.</li>
<li><strong>Comment authors:</strong> name, email address (not displayed publicly), and optional website URL.</li>
<li><strong>Analytics:</strong> anonymous pageview data collected via server-side counters. No third-party tracking pixels.</li>
</ul>
<h2>How We Use Your Information</h2>
<p>Your email address is used solely to deliver the newsletter you subscribed to. We do not sell, rent, or share your personal data with third parties for marketing purposes.</p>
<h2>Cookies</h2>
<p>We use essential cookies for site functionality. You can disable cookies in your browser settings, though this may affect site features.</p>
<h2>Your Rights</h2>
<p>You may request access to, correction of, or deletion of your personal data at any time by contacting <a href="mailto:privacy@zimbabwenewsonline.com">privacy@zimbabwenewsonline.com</a>.</p>
<h2>Changes to This Policy</h2>
<p>We may update this policy periodically. Continued use of the site constitutes acceptance of the revised policy.</p>'),

('terms-of-use',
 'Terms of Use',
 'Terms and conditions for using Zimbabwe News Online.',
 '<h2>Terms of Use</h2>
<p>By accessing or using Zimbabwe News Online, you agree to be bound by these terms. If you do not agree, please discontinue use of the site.</p>
<h2>Intellectual Property</h2>
<p>All content published on Zimbabwe News Online — including articles, photographs, graphics, and video — is protected by copyright. You may not reproduce, distribute, or republish our content without prior written permission.</p>
<h2>User Conduct</h2>
<p>You agree not to use this platform to post or transmit unlawful, harmful, threatening, abusive, defamatory, or otherwise objectionable content. We reserve the right to remove content and suspend access for violations.</p>
<h2>Comments</h2>
<p>User comments are moderated. By submitting a comment you grant us a non-exclusive licence to publish it. We are not responsible for the opinions expressed in user comments.</p>
<h2>Disclaimer</h2>
<p>Zimbabwe News Online strives for accuracy but does not warrant that all content is error-free or complete. We are not liable for any loss arising from reliance on our content.</p>
<h2>Changes to These Terms</h2>
<p>We may update these terms at any time. Continued use of the site constitutes acceptance of the revised terms. Last updated: 2026.</p>')

ON CONFLICT (slug) DO NOTHING;


----------------------------------------------------
-- MIGRATION: 005_views.sql
----------------------------------------------------

-- ============================================================
-- 005_views.sql
-- Article view tracking (daily buckets) + analytics RPCs
-- Depends on: 001_profiles_roles.sql, 003_articles.sql
-- ============================================================

-- ── article_views_daily ───────────────────────────────────────────────────────
-- One row per (article, day). Written ONLY via record_article_view() RPC.
-- Public users cannot insert or update directly — enforced by RLS + no policy.
create table article_views_daily (
  id          uuid    primary key default gen_random_uuid(),
  article_id  uuid    not null references articles(id) on delete cascade,
  day         date    not null default current_date,
  view_count  bigint  not null default 0,

  constraint uq_article_views_day unique (article_id, day),
  constraint chk_view_count check (view_count >= 0)
);

-- Primary query pattern: views for one article over a date range
create index idx_views_article_day
  on article_views_daily(article_id, day desc);

-- Aggregate across all articles for a given day (dashboard overview)
create index idx_views_day
  on article_views_daily(day desc);

-- ── RLS: article_views_daily ─────────────────────────────────────────────────
alter table article_views_daily enable row level security;

-- Only staff can read raw view data; public never needs it.
-- There is intentionally NO insert/update policy — the RPC runs as
-- security definer and bypasses RLS.
create policy "Staff can read view data"
  on article_views_daily for select
  using (is_staff());

-- ── RPC: record_article_view ─────────────────────────────────────────────────
-- Called by POST /api/views.
-- Validates the article is PUBLISHED before counting.
-- Upserts the daily row and increments the denormalised view_count on articles.
create or replace function record_article_view(p_article_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  -- Guard: only count views on published articles
  if not exists (
    select 1 from articles
    where id = p_article_id and status = 'PUBLISHED'
  ) then
    return;
  end if;

  -- Upsert today's daily bucket
  insert into article_views_daily (article_id, day, view_count)
  values (p_article_id, current_date, 1)
  on conflict (article_id, day)
  do update set view_count = article_views_daily.view_count + 1;

  -- Increment the denormalised rolling total
  update articles
  set view_count = view_count + 1
  where id = p_article_id;
end;
$$;

-- ── RPC: most_read_24h ────────────────────────────────────────────────────────
-- Top N articles by views in the last 24 hours.
-- Used by: homepage Most Read widget, article page sidebar.
create or replace function most_read_24h(p_limit int default 5)
returns table (
  article_id     uuid,
  title          text,
  slug           text,
  hero_image_url text,
  total_views    bigint
) language sql security definer stable set search_path = public as $$
  select
    a.id,
    a.title,
    a.slug,
    a.hero_image_url,
    coalesce(sum(v.view_count), 0) as total_views
  from articles a
  left join article_views_daily v
    on v.article_id = a.id
    and v.day >= current_date - interval '1 day'
  where a.status = 'PUBLISHED'
  group by a.id, a.title, a.slug, a.hero_image_url
  order by total_views desc, a.published_at desc
  limit p_limit;
$$;

-- ── RPC: most_read_7d ─────────────────────────────────────────────────────────
-- Top N articles by views over the last 7 days.
-- Used by: admin analytics dashboard.
create or replace function most_read_7d(p_limit int default 10)
returns table (
  article_id     uuid,
  title          text,
  slug           text,
  hero_image_url text,
  total_views    bigint
) language sql security definer stable set search_path = public as $$
  select
    a.id,
    a.title,
    a.slug,
    a.hero_image_url,
    coalesce(sum(v.view_count), 0) as total_views
  from articles a
  left join article_views_daily v
    on v.article_id = a.id
    and v.day >= current_date - interval '7 days'
  where a.status = 'PUBLISHED'
  group by a.id, a.title, a.slug, a.hero_image_url
  order by total_views desc, a.published_at desc
  limit p_limit;
$$;

-- ── RPC: views_series ─────────────────────────────────────────────────────────
-- Daily view series for a single article over a rolling window.
-- Used by: article analytics chart in the admin editor.
create or replace function views_series(
  p_article_id uuid,
  p_days       int default 30
)
returns table (
  day        date,
  view_count bigint
) language sql security definer stable set search_path = public as $$
  select
    gs.day::date,
    coalesce(v.view_count, 0) as view_count
  from generate_series(
    current_date - (p_days - 1) * interval '1 day',
    current_date,
    interval '1 day'
  ) as gs(day)
  left join article_views_daily v
    on v.article_id = p_article_id
    and v.day = gs.day::date
  order by gs.day asc;
$$;

-- ── RPC: top_articles ─────────────────────────────────────────────────────────
-- Top N articles by views over a configurable day window.
-- Used by: admin analytics page.
create or replace function top_articles(
  p_days  int default 7,
  p_limit int default 20
)
returns table (
  article_id     uuid,
  title          text,
  slug           text,
  category_name  text,
  hero_image_url text,
  total_views    bigint,
  published_at   timestamptz
) language sql security definer stable set search_path = public as $$
  select
    a.id,
    a.title,
    a.slug,
    c.name                               as category_name,
    a.hero_image_url,
    coalesce(sum(v.view_count), 0)       as total_views,
    a.published_at
  from articles a
  left join categories c
    on c.id = a.category_id
  left join article_views_daily v
    on v.article_id = a.id
    and v.day >= current_date - (p_days - 1) * interval '1 day'
  where a.status = 'PUBLISHED'
  group by
    a.id, a.title, a.slug, c.name, a.hero_image_url, a.published_at
  order by total_views desc, a.published_at desc
  limit p_limit;
$$;

-- ── Grants ────────────────────────────────────────────────────────────────────
-- Public RPCs (called from /api/views and public components)
grant execute on function record_article_view(uuid)  to anon, authenticated;
grant execute on function most_read_24h(int)          to anon, authenticated;
grant execute on function most_read_7d(int)           to anon, authenticated;
-- Admin-only RPCs
grant execute on function views_series(uuid, int)     to authenticated;
grant execute on function top_articles(int, int)      to authenticated;


----------------------------------------------------
-- MIGRATION: 005b_rpc_functions.sql
----------------------------------------------------

-- ============================================================
-- Zimbabwe News Online — RPC / Analytics Functions
-- ============================================================

-- ── record_article_view ───────────────────────────────────────────────────────
-- Called by the public-facing API route to increment view counts safely.
-- Runs as security definer so it can write to article_views_daily
-- and articles.view_count without exposing direct table writes.
create or replace function record_article_view(p_article_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  -- Upsert daily row
  insert into article_views_daily (article_id, day, view_count)
  values (p_article_id, current_date, 1)
  on conflict (article_id, day)
  do update set view_count = article_views_daily.view_count + 1;

  -- Increment rolling total on the article
  update articles
  set view_count = view_count + 1
  where id = p_article_id;
end;
$$;

-- ── most_read_24h ─────────────────────────────────────────────────────────────
create or replace function most_read_24h(p_limit int default 5)
returns table (
  article_id    uuid,
  title         text,
  slug          text,
  hero_image_url text,
  total_views   bigint
) language sql security definer stable set search_path = public as $$
  select
    a.id           as article_id,
    a.title,
    a.slug,
    a.hero_image_url,
    coalesce(sum(v.view_count), 0) as total_views
  from articles a
  left join article_views_daily v
    on v.article_id = a.id
    and v.day >= current_date - interval '1 day'
  where a.status = 'PUBLISHED'
  group by a.id, a.title, a.slug, a.hero_image_url
  order by total_views desc, a.published_at desc
  limit p_limit;
$$;

-- ── most_read_7d ──────────────────────────────────────────────────────────────
create or replace function most_read_7d(p_limit int default 10)
returns table (
  article_id     uuid,
  title          text,
  slug           text,
  hero_image_url text,
  total_views    bigint
) language sql security definer stable set search_path = public as $$
  select
    a.id           as article_id,
    a.title,
    a.slug,
    a.hero_image_url,
    coalesce(sum(v.view_count), 0) as total_views
  from articles a
  left join article_views_daily v
    on v.article_id = a.id
    and v.day >= current_date - interval '7 days'
  where a.status = 'PUBLISHED'
  group by a.id, a.title, a.slug, a.hero_image_url
  order by total_views desc, a.published_at desc
  limit p_limit;
$$;

-- ── views_series ──────────────────────────────────────────────────────────────
-- Returns daily view counts for a specific article over a date range.
create or replace function views_series(
  p_article_id uuid,
  p_days       int default 30
)
returns table (
  day        date,
  view_count bigint
) language sql security definer stable set search_path = public as $$
  select
    gs.day::date,
    coalesce(v.view_count, 0) as view_count
  from generate_series(
    current_date - (p_days - 1) * interval '1 day',
    current_date,
    interval '1 day'
  ) as gs(day)
  left join article_views_daily v
    on v.article_id = p_article_id
    and v.day = gs.day::date
  order by gs.day;
$$;

-- ── top_articles ──────────────────────────────────────────────────────────────
-- Admin dashboard: top articles by views in a given day range.
create or replace function top_articles(
  p_days  int default 7,
  p_limit int default 20
)
returns table (
  article_id     uuid,
  title          text,
  slug           text,
  category_name  text,
  hero_image_url text,
  total_views    bigint,
  published_at   timestamptz
) language sql security definer stable set search_path = public as $$
  select
    a.id           as article_id,
    a.title,
    a.slug,
    c.name         as category_name,
    a.hero_image_url,
    coalesce(sum(v.view_count), 0) as total_views,
    a.published_at
  from articles a
  left join categories c on c.id = a.category_id
  left join article_views_daily v
    on v.article_id = a.id
    and v.day >= current_date - (p_days - 1) * interval '1 day'
  where a.status = 'PUBLISHED'
  group by a.id, a.title, a.slug, c.name, a.hero_image_url, a.published_at
  order by total_views desc, a.published_at desc
  limit p_limit;
$$;

-- ── insert_audit_log ─────────────────────────────────────────────────────────
-- Server-side helper to write audit entries safely.
create or replace function insert_audit_log(
  p_user_id     uuid,
  p_action      text,
  p_target_table text default null,
  p_target_id   uuid default null,
  p_payload     jsonb default null,
  p_ip_address  inet default null
)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into audit_logs (user_id, action, target_table, target_id, payload, ip_address)
  values (p_user_id, p_action, p_target_table, p_target_id, p_payload, p_ip_address);
end;
$$;

-- ── Grant execute to anon/authenticated for public RPCs ───────────────────────
grant execute on function record_article_view(uuid)   to anon, authenticated;
grant execute on function most_read_24h(int)          to anon, authenticated;
grant execute on function most_read_7d(int)           to anon, authenticated;
-- views_series and top_articles are admin-only
grant execute on function views_series(uuid, int)     to authenticated;
grant execute on function top_articles(int, int)      to authenticated;


----------------------------------------------------
-- MIGRATION: 006_comments.sql
----------------------------------------------------

-- ============================================================
-- 006_comments.sql
-- Comments, threading, and moderation audit log
-- Depends on: 001_profiles_roles.sql, 003_articles.sql
-- ============================================================

-- ── Enum: comment moderation states ──────────────────────────────────────────
create type comment_status as enum (
  'PENDING',    -- Awaiting moderation (default)
  'APPROVED',   -- Visible to the public
  'REJECTED',   -- Declined — not spam, but off-topic / rule-breaking
  'SPAM',       -- Flagged as spam
  'DELETED'     -- Soft-deleted (kept for audit; never shown)
);

-- ── comments ─────────────────────────────────────────────────────────────────
create table comments (
  id               uuid           primary key default gen_random_uuid(),
  article_id       uuid           not null references articles(id) on delete cascade,
  -- Self-referencing for threaded replies (max one level recommended for news)
  parent_id        uuid           references comments(id) on delete cascade,

  -- ── Commenter (no auth required) ──────────────────────────────────────────
  author_name      text           not null,
  author_email     citext         not null,
  author_url       text,           -- Optional website link

  -- ── Content ───────────────────────────────────────────────────────────────
  body             text           not null,

  -- ── Moderation ────────────────────────────────────────────────────────────
  status           comment_status not null default 'PENDING',
  moderated_by     uuid           references auth.users(id) on delete set null,
  moderated_at     timestamptz,
  moderation_note  text,           -- Internal note visible only to moderators

  -- ── Anti-abuse fingerprinting (never exposed to public) ───────────────────
  -- SHA-256(ip_address + salt). Used for rate-limiting and spam detection.
  ip_hash          text,
  user_agent_hash  text,

  -- ── Timestamps ────────────────────────────────────────────────────────────
  created_at       timestamptz    not null default now(),
  updated_at       timestamptz    not null default now(),

  -- ── Constraints ───────────────────────────────────────────────────────────
  constraint chk_comment_body_length    check (char_length(body) between 1 and 2000),
  constraint chk_comment_author_name    check (char_length(author_name) between 1 and 100),
  constraint chk_author_url_format      check (
    author_url is null
    or author_url ~* '^https?://'
  ),
  constraint chk_moderation_consistency check (
    -- moderated_by and moderated_at must both be set or both be null
    (moderated_by is null) = (moderated_at is null)
  ),
  constraint chk_no_self_parent check (parent_id <> id)
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Public comment feed for an article (approved only, chronological)
create index idx_comments_article_approved
  on comments(article_id, created_at asc)
  where status = 'APPROVED';

-- Admin moderation queue (by status, newest first)
create index idx_comments_status_date
  on comments(status, created_at desc);

-- Article-level moderation view (all statuses)
create index idx_comments_article_status
  on comments(article_id, status, created_at desc);

-- Thread lookup
create index idx_comments_parent_id
  on comments(parent_id)
  where parent_id is not null;

create trigger trg_comments_updated_at
  before update on comments
  for each row execute procedure set_updated_at();

-- ── comment_moderation_log ───────────────────────────────────────────────────
-- Immutable audit trail for every moderation decision.
-- Append-only: no UPDATE or DELETE policies.
create table comment_moderation_log (
  id            uuid        primary key default gen_random_uuid(),
  comment_id    uuid        not null references comments(id) on delete cascade,
  moderator_id  uuid        references auth.users(id) on delete set null,
  -- Action taken: mirrors comment_status values + 'RESTORED'
  action        text        not null,
  -- Reason / internal note
  note          text,
  created_at    timestamptz not null default now(),

  constraint chk_moderation_action check (
    action in ('APPROVED', 'REJECTED', 'SPAM', 'DELETED', 'RESTORED', 'PENDING')
  )
);

create index idx_mod_log_comment    on comment_moderation_log(comment_id, created_at desc);
create index idx_mod_log_moderator  on comment_moderation_log(moderator_id, created_at desc);

-- ── RLS: comments ────────────────────────────────────────────────────────────
alter table comments                enable row level security;
alter table comment_moderation_log  enable row level security;

-- Public: only APPROVED comments
create policy "Public reads approved comments"
  on comments for select
  using (status = 'APPROVED' or is_moderator());

-- Anyone can submit a comment; application layer sets status = 'PENDING'.
create policy "Anyone can submit comments"
  on comments for insert
  with check (status = 'PENDING');

-- Only moderators can change status, add notes, etc.
create policy "Moderators can update comments"
  on comments for update
  using (is_moderator());

create policy "Moderators can delete comments"
  on comments for delete
  using (is_moderator());

-- ── RLS: comment_moderation_log ──────────────────────────────────────────────
-- Only admins read; inserts happen in server actions (authenticated role).
create policy "Admins can read moderation log"
  on comment_moderation_log for select
  using (is_admin());

create policy "Moderators can append to moderation log"
  on comment_moderation_log for insert
  with check (is_moderator());


----------------------------------------------------
-- MIGRATION: 007_newsletter.sql
----------------------------------------------------

-- ============================================================
-- 007_newsletter.sql
-- Newsletter subscribers with double-opt-in and unsubscribe tokens
-- Depends on: 001_profiles_roles.sql
-- ============================================================

-- ── newsletter_subscribers ────────────────────────────────────────────────────
create table newsletter_subscribers (
  id                  uuid        primary key default gen_random_uuid(),
  email               citext      not null,

  -- ── Consent state ─────────────────────────────────────────────────────────
  confirmed           boolean     not null default false,
  confirmed_at        timestamptz,

  -- ── Tokens ────────────────────────────────────────────────────────────────
  -- Used in the double-opt-in confirmation email link.
  confirmation_token  text        unique default encode(gen_random_bytes(32), 'hex'),
  -- Used in all unsubscribe links. Separate from confirmation_token so that
  -- the act of confirming does not expose the unsubscribe token, and vice versa.
  unsubscribe_token   text        unique not null default encode(gen_random_bytes(32), 'hex'),

  -- ── Attribution ───────────────────────────────────────────────────────────
  -- Where the subscription originated (e.g. 'website', 'article_footer', 'admin')
  source              text        not null default 'website',

  -- ── Lifecycle ─────────────────────────────────────────────────────────────
  subscribed_at       timestamptz not null default now(),
  unsubscribed_at     timestamptz,

  -- ── Constraints ───────────────────────────────────────────────────────────
  constraint uq_newsletter_email          unique (email),
  constraint chk_email_format             check (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$'),
  -- confirmed_at must be set when confirmed = true
  constraint chk_confirmed_at_consistency check (
    (confirmed = false) or (confirmed_at is not null)
  ),
  -- Cannot be both confirmed and unsubscribed at the same time
  -- (re-subscribe first resets unsubscribed_at)
  constraint chk_not_both_states check (
    not (confirmed = true and unsubscribed_at is not null)
    or unsubscribed_at is not null  -- allow unsubscribed after confirmed
  )
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- Admin lookup by email
create index idx_newsletter_email
  on newsletter_subscribers(email);

-- Admin list: confirmed subscribers, newest first
create index idx_newsletter_confirmed_date
  on newsletter_subscribers(confirmed, subscribed_at desc);

-- Token lookups (confirmation and unsubscribe links)
-- Partial indexes on active rows only for speed
create index idx_newsletter_confirmation_token
  on newsletter_subscribers(confirmation_token)
  where confirmed = false and confirmation_token is not null;

create index idx_newsletter_unsubscribe_token
  on newsletter_subscribers(unsubscribe_token)
  where unsubscribed_at is null;

-- Source attribution reporting
create index idx_newsletter_source
  on newsletter_subscribers(source, subscribed_at desc);

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table newsletter_subscribers enable row level security;

-- Only admins can read the subscriber list (PII protection)
create policy "Admins can read subscribers"
  on newsletter_subscribers for select
  using (is_admin());

-- Anyone can subscribe (unauthenticated POST /api/newsletter/subscribe)
create policy "Anyone can subscribe"
  on newsletter_subscribers for insert
  with check (true);

-- Admins update (confirm, re-activate) and manage subscribers
create policy "Admins can update subscribers"
  on newsletter_subscribers for update
  using (is_admin());

create policy "Admins can delete subscribers"
  on newsletter_subscribers for delete
  using (is_admin());


----------------------------------------------------
-- MIGRATION: 008_settings_audit.sql
----------------------------------------------------

-- ============================================================
-- 008_settings_audit.sql
-- Site settings (key/value store) and immutable audit log
-- Depends on: 001_profiles_roles.sql
-- ============================================================

-- ── site_settings ─────────────────────────────────────────────────────────────
-- Key/value table for runtime configuration.
-- Changes tracked in audit_logs via insert_audit_log() RPC.
create table site_settings (
  key          text        primary key,
  value        text        not null,
  -- Human-readable description of what the setting controls
  description  text,
  updated_by   uuid        references auth.users(id) on delete set null,
  updated_at   timestamptz not null default now()
);

-- ── Default settings seed ────────────────────────────────────────────────────
insert into site_settings (key, value, description) values
  ('site_name',          'Zimbabwe News Online',
   'Display name used in the site header, OG tags, and emails'),
  ('site_description',   'Breaking news and in-depth coverage from Zimbabwe and across Africa.',
   'Default meta description for the homepage'),
  ('contact_email',      'newsroom@zimbabwenewsonline.com',
   'Public newsroom contact email shown on the contact page'),
  ('twitter_handle',     '',
   'Twitter handle without the @ symbol'),
  ('facebook_url',       '',
   'Full URL of the Facebook page'),
  ('comments_enabled',   'true',
   'Set to "false" to disable comment submission site-wide'),
  ('newsletter_enabled', 'true',
   'Set to "false" to hide the newsletter signup form site-wide'),
  ('breaking_auto_expire_hours', '24',
   'Hours after which breaking news status is automatically expired');

-- ── audit_logs ────────────────────────────────────────────────────────────────
-- Append-only record of security-sensitive and editorially important actions.
-- Written via insert_audit_log() security-definer RPC — clients never write directly.
create table audit_logs (
  id            uuid        primary key default gen_random_uuid(),
  -- NULL when action is performed by an unauthenticated process / system
  user_id       uuid        references auth.users(id) on delete set null,

  -- Dot-namespaced action identifier, e.g. 'article.publish', 'comment.approve'
  action        text        not null,

  -- The table and primary key of the affected row (for fast lookup)
  target_table  text,
  target_id     uuid,

  -- JSON snapshots for diffing (old_values only set on UPDATE / DELETE)
  old_values    jsonb,
  new_values    jsonb,

  -- Request context
  ip_address    inet,
  user_agent    text,

  created_at    timestamptz not null default now(),

  constraint chk_audit_action_format check (action ~ '^[a-z_]+\.[a-z_]+$')
);

-- ── Indexes ───────────────────────────────────────────────────────────────────

-- User activity feed
create index idx_audit_user_date
  on audit_logs(user_id, created_at desc);

-- Entity history (e.g. all changes to a specific article)
create index idx_audit_target
  on audit_logs(target_table, target_id, created_at desc);

-- Action-type reporting (e.g. all publish events)
create index idx_audit_action_date
  on audit_logs(action, created_at desc);

-- Overall chronological feed
create index idx_audit_created_at
  on audit_logs(created_at desc);

-- ── RPC: insert_audit_log ────────────────────────────────────────────────────
-- Called from server actions and route handlers.
-- Runs as security definer so it can always write audit_logs
-- regardless of the caller's RLS context.
create or replace function insert_audit_log(
  p_action       text,
  p_target_table text    default null,
  p_target_id    uuid    default null,
  p_old_values   jsonb   default null,
  p_new_values   jsonb   default null,
  p_ip_address   inet    default null,
  p_user_agent   text    default null
)
returns void language plpgsql security definer set search_path = public as $$
begin
  -- Validate action format (e.g. 'article.publish')
  if p_action !~ '^[a-z_]+\.[a-z_]+$' then
    raise exception 'Invalid audit action format: %', p_action;
  end if;

  insert into audit_logs (
    user_id,
    action,
    target_table,
    target_id,
    old_values,
    new_values,
    ip_address,
    user_agent
  ) values (
    auth.uid(),
    p_action,
    p_target_table,
    p_target_id,
    p_old_values,
    p_new_values,
    p_ip_address,
    p_user_agent
  );
end;
$$;

grant execute on function insert_audit_log(text, text, uuid, jsonb, jsonb, inet, text)
  to authenticated;

-- ── RLS: site_settings ────────────────────────────────────────────────────────
alter table site_settings enable row level security;

-- Any staff member can read settings (needed for conditional feature flags)
create policy "Staff can read site settings"
  on site_settings for select
  using (is_staff());

-- Only admins can modify settings
create policy "Admins can manage site settings"
  on site_settings for all
  using (is_admin());

-- ── RLS: audit_logs ──────────────────────────────────────────────────────────
alter table audit_logs enable row level security;

-- Admins can read; nobody has a direct insert/update/delete policy.
-- All writes go through insert_audit_log() which runs as security definer.
create policy "Admins can read audit logs"
  on audit_logs for select
  using (is_admin());


----------------------------------------------------
-- MIGRATION: 009_rls.sql
----------------------------------------------------

-- ============================================================
-- 009_rls.sql
-- Comprehensive, idempotent Row Level Security for all tables.
-- Supersedes the inline RLS blocks in 001–008.
-- Depends on: 001_profiles_roles.sql (RBAC helper functions)
-- ============================================================

-- ── Helper: ownership check for articles ─────────────────────────────────────
-- Returns true when the calling authenticated user authored the given article.
-- Used in WITH CHECK clauses to prevent authors from touching others' work.
create or replace function is_article_author(p_author_id uuid)
returns boolean language sql security definer stable set search_path = public as $$
  select auth.uid() is not null and auth.uid() = p_author_id;
$$;

-- ── Helper: check whether status transition is author-safe ───────────────────
-- Authors may write DRAFT or REVIEW only; PUBLISHED/ARCHIVED require editor+.
create or replace function is_author_safe_status(p_status text)
returns boolean language sql immutable as $$
  select p_status in ('DRAFT', 'REVIEW');
$$;

-- ═════════════════════════════════════════════════════════════════════════════
-- profiles
-- ═════════════════════════════════════════════════════════════════════════════
alter table profiles enable row level security;

drop policy if exists "Public can view profiles"               on profiles;
drop policy if exists "Users can update their own profile"     on profiles;
drop policy if exists "Users can upsert their own profile"     on profiles;

-- Any visitor can see profile display data (used for article bylines).
create policy "Public can view profiles"
  on profiles for select
  using (true);

-- A user may only update their own row.
create policy "Users can update their own profile"
  on profiles for update
  using  (auth.uid() = id)
  with check (auth.uid() = id);

-- Allow the handle_new_user() trigger path via service role;
-- direct client inserts are blocked (no anon/authenticated insert policy).

-- ═════════════════════════════════════════════════════════════════════════════
-- user_roles
-- ═════════════════════════════════════════════════════════════════════════════
alter table user_roles enable row level security;

drop policy if exists "Staff can view roles"        on user_roles;
drop policy if exists "Admins can manage roles"     on user_roles;
drop policy if exists "Admins can insert roles"     on user_roles;
drop policy if exists "Admins can update roles"     on user_roles;
drop policy if exists "Admins can delete roles"     on user_roles;

-- Any authenticated staff member may read the role table (needed for RBAC
-- functions to resolve their own role without privilege escalation).
create policy "Staff can view roles"
  on user_roles for select
  using (is_staff());

-- Only admins may grant or revoke roles.
create policy "Admins can insert roles"
  on user_roles for insert
  with check (is_admin());

create policy "Admins can update roles"
  on user_roles for update
  using  (is_admin())
  with check (is_admin());

create policy "Admins can delete roles"
  on user_roles for delete
  using (is_admin());

-- ═════════════════════════════════════════════════════════════════════════════
-- categories
-- ═════════════════════════════════════════════════════════════════════════════
alter table categories enable row level security;

drop policy if exists "Categories are publicly readable"   on categories;
drop policy if exists "Editors can manage categories"      on categories;
drop policy if exists "Editors can insert categories"      on categories;
drop policy if exists "Editors can update categories"      on categories;
drop policy if exists "Editors can delete categories"      on categories;

-- Public nav menus and article pages need category data.
create policy "Categories are publicly readable"
  on categories for select
  using (true);

-- Only editors+ may create, rename, or remove categories.
create policy "Editors can insert categories"
  on categories for insert
  with check (is_editor());

create policy "Editors can update categories"
  on categories for update
  using  (is_editor())
  with check (is_editor());

create policy "Editors can delete categories"
  on categories for delete
  using (is_editor());

-- ═════════════════════════════════════════════════════════════════════════════
-- tags
-- ═════════════════════════════════════════════════════════════════════════════
alter table tags enable row level security;

drop policy if exists "Tags are publicly readable"  on tags;
drop policy if exists "Authors can manage tags"     on tags;
drop policy if exists "Authors can insert tags"     on tags;
drop policy if exists "Authors can update tags"     on tags;
drop policy if exists "Editors can delete tags"     on tags;

-- Tags appear on public article pages.
create policy "Tags are publicly readable"
  on tags for select
  using (true);

-- Any staff author or above may create new tags (needed when filing articles).
create policy "Authors can insert tags"
  on tags for insert
  with check (is_author());

-- Renaming a tag is an editorial action; restrict to editor+.
create policy "Editors can update tags"
  on tags for update
  using  (is_editor())
  with check (is_editor());

-- Deleting a tag is destructive (cascades to article_tags); editor+ only.
create policy "Editors can delete tags"
  on tags for delete
  using (is_editor());

-- ═════════════════════════════════════════════════════════════════════════════
-- articles
-- ═════════════════════════════════════════════════════════════════════════════
alter table articles enable row level security;

drop policy if exists "Published articles are public"                        on articles;
drop policy if exists "Authors can create articles"                          on articles;
drop policy if exists "Authors update own articles; editors update any"      on articles;
drop policy if exists "Editors can delete articles"                          on articles;
drop policy if exists "Public reads published articles"                      on articles;
drop policy if exists "Authors read own articles"                            on articles;
drop policy if exists "Editors read all articles"                            on articles;
drop policy if exists "Authors insert own articles"                          on articles;
drop policy if exists "Authors update own draft articles"                    on articles;
drop policy if exists "Editors update any article"                           on articles;

-- Public: PUBLISHED articles only.
create policy "Public reads published articles"
  on articles for select
  using (status = 'PUBLISHED');

-- Authors: read their own articles regardless of status (drafts, review, etc.)
create policy "Authors read own articles"
  on articles for select
  using (is_author() and auth.uid() = author_id);

-- Editors+: read everything (all statuses, all authors).
create policy "Editors read all articles"
  on articles for select
  using (is_editor());

-- Authors may create articles only for themselves and only in non-published states.
create policy "Authors insert own articles"
  on articles for insert
  with check (
    is_author()
    and auth.uid() = author_id
    and is_author_safe_status(status::text)
  );

-- Authors may update their own articles but cannot set status to PUBLISHED/ARCHIVED.
create policy "Authors update own draft articles"
  on articles for update
  using  (is_author() and auth.uid() = author_id and status in ('DRAFT', 'REVIEW'))
  with check (
    is_author()
    and auth.uid() = author_id
    and is_author_safe_status(status::text)
  );

-- Editors may update any article and set any status (including PUBLISHED).
create policy "Editors update any article"
  on articles for update
  using  (is_editor())
  with check (is_editor());

-- Only editors+ may delete articles.
create policy "Editors delete articles"
  on articles for delete
  using (is_editor());

-- ═════════════════════════════════════════════════════════════════════════════
-- article_tags
-- ═════════════════════════════════════════════════════════════════════════════
alter table article_tags enable row level security;

drop policy if exists "Article tags are publicly readable"  on article_tags;
drop policy if exists "Authors can manage article tags"     on article_tags;
drop policy if exists "Public reads article tags"           on article_tags;
drop policy if exists "Authors manage own article tags"     on article_tags;
drop policy if exists "Editors manage any article tags"     on article_tags;

-- Tag join is needed for public article pages and tag listing pages.
create policy "Public reads article tags"
  on article_tags for select
  using (true);

-- Authors may manage tags only on articles they authored.
create policy "Authors manage own article tags"
  on article_tags for insert
  with check (
    is_author()
    and exists (
      select 1 from articles
      where id = article_id and author_id = auth.uid()
    )
  );

create policy "Authors delete own article tags"
  on article_tags for delete
  using (
    is_author()
    and exists (
      select 1 from articles
      where id = article_id and author_id = auth.uid()
    )
  );

-- Editors may manage tags on any article.
create policy "Editors manage any article tags"
  on article_tags for insert
  with check (is_editor());

create policy "Editors delete any article tags"
  on article_tags for delete
  using (is_editor());

-- ═════════════════════════════════════════════════════════════════════════════
-- media
-- ═════════════════════════════════════════════════════════════════════════════
alter table media enable row level security;

drop policy if exists "Media is publicly readable"              on media;
drop policy if exists "Staff can upload media"                  on media;
drop policy if exists "Uploaders and editors can update media"  on media;
drop policy if exists "Editors can delete media"                on media;

-- Media URLs are public CDN links; metadata must be readable for rendering.
create policy "Media is publicly readable"
  on media for select
  using (true);

-- Only authenticated staff (author+) may upload.
create policy "Authors can upload media"
  on media for insert
  with check (
    is_author()
    and auth.uid() = uploaded_by
  );

-- Uploaders may update their own assets' metadata; editors may update any.
create policy "Uploaders update own media"
  on media for update
  using  (is_author() and uploaded_by = auth.uid())
  with check (is_author() and uploaded_by = auth.uid());

create policy "Editors update any media"
  on media for update
  using  (is_editor())
  with check (is_editor());

-- Only editors+ may delete media records (also requires Storage object removal
-- at the application layer).
create policy "Editors delete media"
  on media for delete
  using (is_editor());

-- ═════════════════════════════════════════════════════════════════════════════
-- article_media
-- ═════════════════════════════════════════════════════════════════════════════
alter table article_media enable row level security;

drop policy if exists "Article media is publicly readable"  on article_media;
drop policy if exists "Authors can manage article media"    on article_media;
drop policy if exists "Public reads article media"          on article_media;
drop policy if exists "Authors manage own article media"    on article_media;
drop policy if exists "Editors manage any article media"    on article_media;

-- Needed to render inline images in published articles.
create policy "Public reads article media"
  on article_media for select
  using (true);

-- Authors may attach media only to their own articles.
create policy "Authors manage own article media"
  on article_media for insert
  with check (
    is_author()
    and exists (
      select 1 from articles
      where id = article_id and author_id = auth.uid()
    )
  );

create policy "Authors delete own article media"
  on article_media for delete
  using (
    is_author()
    and exists (
      select 1 from articles
      where id = article_id and author_id = auth.uid()
    )
  );

-- Editors may attach or remove media on any article.
create policy "Editors manage any article media"
  on article_media for insert
  with check (is_editor());

create policy "Editors delete any article media"
  on article_media for delete
  using (is_editor());

-- ═════════════════════════════════════════════════════════════════════════════
-- article_views_daily
-- ═════════════════════════════════════════════════════════════════════════════
alter table article_views_daily enable row level security;

drop policy if exists "Staff can read view data"  on article_views_daily;

-- Raw view data is an internal metric; staff only.
-- No INSERT/UPDATE/DELETE policies exist by design.
-- All writes go through record_article_view() (security definer), which
-- bypasses RLS entirely. Public and authenticated roles cannot write directly.
create policy "Staff can read view data"
  on article_views_daily for select
  using (is_staff());

-- ═════════════════════════════════════════════════════════════════════════════
-- comments
-- ═════════════════════════════════════════════════════════════════════════════
alter table comments enable row level security;

drop policy if exists "Public reads approved comments"   on comments;
drop policy if exists "Anyone can submit comments"       on comments;
drop policy if exists "Moderators can update comments"   on comments;
drop policy if exists "Moderators can delete comments"   on comments;
drop policy if exists "Moderators read all comments"     on comments;

-- Public: only APPROVED comments are visible.
create policy "Public reads approved comments"
  on comments for select
  using (status = 'APPROVED');

-- Moderators+: read all statuses (moderation queue).
create policy "Moderators read all comments"
  on comments for select
  using (is_moderator());

-- Anyone (including unauthenticated) may submit a comment.
-- Enforced constraints:
--   • status must be PENDING (application cannot self-approve)
--   • moderation fields must be null (cannot pre-set moderator identity)
--   • fingerprint hashes are set by the server action, not the client
create policy "Anyone can submit comments"
  on comments for insert
  with check (
    status = 'PENDING'
    and moderated_by   is null
    and moderated_at   is null
    and moderation_note is null
  );

-- Only moderators+ may change comment status, add moderation notes, etc.
-- Public users have no UPDATE policy at all.
create policy "Moderators update comments"
  on comments for update
  using  (is_moderator())
  with check (is_moderator());

-- Moderators may hard-delete comments (soft-delete via status='DELETED' preferred).
create policy "Moderators delete comments"
  on comments for delete
  using (is_moderator());

-- ═════════════════════════════════════════════════════════════════════════════
-- comment_moderation_log
-- ═════════════════════════════════════════════════════════════════════════════
alter table comment_moderation_log enable row level security;

drop policy if exists "Admins can read moderation log"          on comment_moderation_log;
drop policy if exists "Moderators can append to moderation log" on comment_moderation_log;

-- Moderation log is PII-adjacent (actions on user-submitted content); admins only.
create policy "Admins read moderation log"
  on comment_moderation_log for select
  using (is_admin());

-- Moderators may append entries; no UPDATE or DELETE — log is append-only.
create policy "Moderators append to moderation log"
  on comment_moderation_log for insert
  with check (
    is_moderator()
    and auth.uid() = moderator_id
  );

-- ═════════════════════════════════════════════════════════════════════════════
-- newsletter_subscribers
-- ═════════════════════════════════════════════════════════════════════════════
alter table newsletter_subscribers enable row level security;

drop policy if exists "Admins can read subscribers"    on newsletter_subscribers;
drop policy if exists "Anyone can subscribe"           on newsletter_subscribers;
drop policy if exists "Admins can update subscribers"  on newsletter_subscribers;
drop policy if exists "Admins can delete subscribers"  on newsletter_subscribers;

-- Subscriber list is PII; admins only.
create policy "Admins read subscribers"
  on newsletter_subscribers for select
  using (is_admin());

-- Public subscription endpoint.
-- Enforced constraints prevent clients from:
--   • self-confirming (confirmed must be false)
--   • setting confirmed_at
--   • backdating subscribed_at
--   • pre-setting the unsubscribe path
-- Tokens are generated by DB defaults; the application may not supply them.
create policy "Anyone can subscribe"
  on newsletter_subscribers for insert
  with check (
    confirmed       = false
    and confirmed_at  is null
    and unsubscribed_at is null
  );

-- Admins manage the subscriber lifecycle (confirm, reactivate, GDPR delete).
create policy "Admins update subscribers"
  on newsletter_subscribers for update
  using  (is_admin())
  with check (is_admin());

create policy "Admins delete subscribers"
  on newsletter_subscribers for delete
  using (is_admin());

-- ═════════════════════════════════════════════════════════════════════════════
-- site_settings
-- ═════════════════════════════════════════════════════════════════════════════
alter table site_settings enable row level security;

drop policy if exists "Staff can read site settings"     on site_settings;
drop policy if exists "Admins can manage site settings"  on site_settings;
drop policy if exists "Admins insert site settings"      on site_settings;
drop policy if exists "Admins update site settings"      on site_settings;
drop policy if exists "Admins delete site settings"      on site_settings;

-- All staff need to read settings for feature-flag checks (e.g. comments_enabled).
create policy "Staff read site settings"
  on site_settings for select
  using (is_staff());

-- Only admins may create, change, or remove settings.
create policy "Admins insert site settings"
  on site_settings for insert
  with check (is_admin());

create policy "Admins update site settings"
  on site_settings for update
  using  (is_admin())
  with check (is_admin());

create policy "Admins delete site settings"
  on site_settings for delete
  using (is_admin());

-- ═════════════════════════════════════════════════════════════════════════════
-- audit_logs
-- ═════════════════════════════════════════════════════════════════════════════
alter table audit_logs enable row level security;

drop policy if exists "Admins can read audit logs"  on audit_logs;

-- Audit log is security-sensitive; admins only.
-- No INSERT/UPDATE/DELETE policies exist by design.
-- All writes go through insert_audit_log() (security definer), which
-- bypasses RLS. Direct client writes are impossible.
create policy "Admins read audit logs"
  on audit_logs for select
  using (is_admin());

-- ═════════════════════════════════════════════════════════════════════════════
-- Grants for helper functions
-- ═════════════════════════════════════════════════════════════════════════════
grant execute on function is_article_author(uuid) to authenticated;
grant execute on function is_author_safe_status(text) to authenticated;


----------------------------------------------------
-- MIGRATION: 010_article_author_fk.sql
----------------------------------------------------

-- Migration 010: Add FK from articles.author_id → profiles.id
-- This is required for PostgREST to resolve the author:profiles(...) join in ARTICLE_SELECT.
-- Without this FK in the public schema, the join fails with PGRST200 and all article queries return null.

-- Step 1: Ensure every auth.users row has a matching profiles row.
-- (handle_new_user() trigger covers sign-ups, but admin-API-created users may be missing.)
INSERT INTO public.profiles (id, full_name)
SELECT u.id, COALESCE(u.raw_user_meta_data->>'full_name', 'Staff')
FROM auth.users u
WHERE u.id NOT IN (SELECT id FROM public.profiles)
ON CONFLICT (id) DO NOTHING;

-- Step 2: Add the FK constraint.
-- ON DELETE RESTRICT prevents orphaned articles.
ALTER TABLE public.articles
  ADD CONSTRAINT fk_articles_author_profile
  FOREIGN KEY (author_id) REFERENCES public.profiles(id)
  ON DELETE RESTRICT;

-- Optional: set a readable name for any admin user whose full_name is still null.
-- Adjust the WHERE clause to target specific user IDs if needed.
UPDATE public.profiles
SET full_name = 'Admin'
WHERE full_name IS NULL
  AND id IN (
    SELECT user_id FROM public.user_roles WHERE role = 'ADMIN'
  );

----------------------------------------------------
-- MIGRATION: 011_optimize_most_read_rpcs.sql
----------------------------------------------------

-- ============================================================
-- 011_optimize_most_read_rpcs.sql
-- Rewrite most_read_24h and most_read_7d to drive from
-- article_views_daily instead of scanning all published articles.
--
-- Old approach: FROM articles LEFT JOIN article_views_daily
--   → full scan of every published article, GROUP BY all of them,
--     then filter/sort. Cost grows O(total articles).
--
-- New approach: FROM article_views_daily JOIN articles
--   → only rows with actual views in the window are processed.
--     Cost grows O(active articles in window), not total articles.
--     Articles with zero views in the period are correctly absent.
-- ============================================================

CREATE OR REPLACE FUNCTION most_read_24h(p_limit int DEFAULT 5)
RETURNS TABLE (
  article_id     uuid,
  title          text,
  slug           text,
  hero_image_url text,
  total_views    bigint
)
LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT
    a.id           AS article_id,
    a.title,
    a.slug,
    a.hero_image_url,
    SUM(v.view_count) AS total_views
  FROM article_views_daily v
  JOIN articles a ON a.id = v.article_id
  WHERE v.day >= current_date - INTERVAL '1 day'
    AND a.status = 'PUBLISHED'
  GROUP BY a.id, a.title, a.slug, a.hero_image_url
  ORDER BY total_views DESC, a.published_at DESC
  LIMIT p_limit;
$$;

CREATE OR REPLACE FUNCTION most_read_7d(p_limit int DEFAULT 10)
RETURNS TABLE (
  article_id     uuid,
  title          text,
  slug           text,
  hero_image_url text,
  total_views    bigint
)
LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT
    a.id           AS article_id,
    a.title,
    a.slug,
    a.hero_image_url,
    SUM(v.view_count) AS total_views
  FROM article_views_daily v
  JOIN articles a ON a.id = v.article_id
  WHERE v.day >= current_date - INTERVAL '7 days'
    AND a.status = 'PUBLISHED'
  GROUP BY a.id, a.title, a.slug, a.hero_image_url
  ORDER BY total_views DESC, a.published_at DESC
  LIMIT p_limit;
$$;

-- Grants unchanged — these are public RPCs.
GRANT EXECUTE ON FUNCTION most_read_24h(int) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION most_read_7d(int)  TO anon, authenticated;

----------------------------------------------------
-- MIGRATION: 012_storage_bucket.sql
----------------------------------------------------

-- ============================================================
-- 012_storage_bucket.sql
-- Creates the 'media' Supabase Storage bucket and its object
-- access policies.  Also seeds the whatsapp_url site setting.
--
-- The bucket name 'media' matches STORAGE.MEDIA in src/db/schema.ts
-- and the storage_path column in the media table.
--
-- Run this in Supabase Studio → SQL Editor.
-- ============================================================

-- ── Create bucket ─────────────────────────────────────────────────────────────
-- public = true  → objects served at the CDN public URL without a signed URL.
-- file_size_limit = 10 MB (matches MAX_BYTES in MediaLibrary.tsx).
-- allowed_mime_types restricts uploads at the Storage layer as a second defence.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'media',
  'media',
  true,
  10485760,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
ON CONFLICT (id) DO UPDATE SET
  public             = true,
  file_size_limit    = 10485760,
  allowed_mime_types = ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/avif'];

-- ── Storage object policies ───────────────────────────────────────────────────
-- Policies live on storage.objects, not on the media DB table.
-- The DB-level RLS (media table) applies separately to the metadata row.

-- 1. Anyone can read/download public media files (CDN-public bucket).
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage' AND tablename = 'objects'
      AND policyname = 'Public can read media objects'
  ) THEN
    CREATE POLICY "Public can read media objects"
      ON storage.objects FOR SELECT
      USING (bucket_id = 'media');
  END IF;
END $$;

-- 2. Any authenticated user (staff) can upload to the media bucket.
--    The DB-level RLS on the media table (is_author() check) applies separately.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage' AND tablename = 'objects'
      AND policyname = 'Authenticated users can upload media'
  ) THEN
    CREATE POLICY "Authenticated users can upload media"
      ON storage.objects FOR INSERT
      WITH CHECK (
        bucket_id = 'media'
        AND auth.role() = 'authenticated'
      );
  END IF;
END $$;

-- 3. Any authenticated user can delete objects from the media bucket.
--    (DB-level RLS on media table restricts this to editors+ separately.)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage' AND tablename = 'objects'
      AND policyname = 'Authenticated users can delete media'
  ) THEN
    CREATE POLICY "Authenticated users can delete media"
      ON storage.objects FOR DELETE
      USING (
        bucket_id = 'media'
        AND auth.role() = 'authenticated'
      );
  END IF;
END $$;

-- ── Add whatsapp_url setting ──────────────────────────────────────────────────
INSERT INTO site_settings (key, value, description)
VALUES (
  'whatsapp_url',
  '',
  'WhatsApp channel or community link shown in the top navigation bar. Leave empty to hide.'
)
ON CONFLICT (key) DO NOTHING;

-- ── Allow public (anon) to read site_settings ─────────────────────────────────
-- The public layout fetches settings server-side using the service-role client
-- (createAdminClient), which bypasses RLS.  No policy change needed for that path.
-- This policy is kept for completeness if you ever want anon reads directly.
-- It is NOT required for the current implementation.
-- (Leave commented out — the admin client approach is safer.)
-- CREATE POLICY "Public can read site settings"
--   ON site_settings FOR SELECT
--   USING (true);


----------------------------------------------------
-- MIGRATION: 013_is_featured.sql
----------------------------------------------------

-- Migration 013: Add is_featured flag to articles
-- Articles where is_featured = true appear in the hero carousel on the homepage.

ALTER TABLE articles
  ADD COLUMN IF NOT EXISTS is_featured boolean NOT NULL DEFAULT false;

-- Index for fast hero query
CREATE INDEX IF NOT EXISTS idx_articles_is_featured
  ON articles (is_featured, published_at DESC)
  WHERE is_featured = true AND status = 'PUBLISHED';

-- RLS: public read already covered by existing policy on articles.
-- Admin/Editor/Author can update is_featured via existing UPDATE policy.

----------------------------------------------------
-- MIGRATION: 014_is_live.sql
----------------------------------------------------

-- Migration 014: Add is_live flag to articles
-- When is_live = true the article shows a live badge in the Latest Updates section.

ALTER TABLE articles
  ADD COLUMN IF NOT EXISTS is_live boolean NOT NULL DEFAULT false;

-- Index for Latest Updates query (updated_at DESC with is_live prioritised)
CREATE INDEX IF NOT EXISTS idx_articles_updated_at
  ON articles (updated_at DESC)
  WHERE status = 'PUBLISHED';


----------------------------------------------------
-- MIGRATION: 015_top_story_rank.sql
----------------------------------------------------

-- ── Top Story Rank ─────────────────────────────────────────────────────────
-- Allows editors to manually pin up to 6 articles as Top Stories.
-- NULL  = not a top story (default).
-- 1–6   = ranked position (1 is highest priority).
-- The partial unique index enforces one article per rank slot.

ALTER TABLE articles
  ADD COLUMN IF NOT EXISTS top_story_rank integer
    CHECK (top_story_rank >= 1 AND top_story_rank <= 6);

-- One article per rank slot (NULL values are excluded from uniqueness check)
CREATE UNIQUE INDEX IF NOT EXISTS articles_top_story_rank_unique
  ON articles (top_story_rank)
  WHERE top_story_rank IS NOT NULL;

-- Fast lookup for homepage query
CREATE INDEX IF NOT EXISTS articles_top_story_rank_idx
  ON articles (top_story_rank)
  WHERE top_story_rank IS NOT NULL AND status = 'PUBLISHED';


----------------------------------------------------
-- MIGRATION: 016_admin_login_rate_limit.sql
----------------------------------------------------

-- Create admin login attempts tracking table
CREATE TABLE IF NOT EXISTS public.admin_login_attempts (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    email text NOT NULL,
    ip_address text,
    success boolean NOT NULL,
    reason text,
    attempted_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Index for fast failed-login counts (Rate limiting)
CREATE INDEX IF NOT EXISTS idx_admin_login_attempts_recent 
ON public.admin_login_attempts(email, ip_address, attempted_at) 
WHERE success = false;

-- Add RLS rules (Only service role can access)
ALTER TABLE public.admin_login_attempts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role has full access to login attempts"
    ON public.admin_login_attempts
    AS PERMISSIVE FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- Function to record a login attempt
CREATE OR REPLACE FUNCTION public.record_admin_login_attempt(
    p_email text,
    p_ip text,
    p_success boolean,
    p_reason text
) RETURNS void AS $$
BEGIN
    INSERT INTO public.admin_login_attempts (email, ip_address, success, reason)
    VALUES (p_email, p_ip, p_success, p_reason);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to check rate limit (Max 5 failed attempts in 15 minutes)
CREATE OR REPLACE FUNCTION public.check_admin_login_rate_limit(
    p_email text,
    p_ip text
) RETURNS boolean AS $$
DECLARE
    recent_failures integer;
BEGIN
    -- Check if there are 5 or more failed attempts in the last 15 minutes for this email or IP
    SELECT count(*) INTO recent_failures
    FROM public.admin_login_attempts
    WHERE success = false
      AND (email = p_email OR ip_address = p_ip)
      AND attempted_at > now() - interval '15 minutes';

    RETURN recent_failures < 5;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
